<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Каталог салонов");

$domain_arr=explode('.', $_SERVER['HTTP_HOST']);
$domain_name=$domain_arr[0];


global $city_id;

$arFilter = Array('IBLOCK_ID'=>7, 'GLOBAL_ACTIVE'=>'Y', 'CODE'=>$domain_name);
$db_list = CIBlockSection::GetList(Array($by=>$order), $arFilter, true, $arSelect=Array("UF_TITLE", "UF_DESCRIPTION", "UF_KEYWORDS", "UF_H1", "UF_HOME_DESC", "UF_HOME_SEO"));
$city_code="";
if($ar_result = $db_list->GetNext())
{
    $city_code=$ar_result['CODE'];
    $city_id=$ar_result['ID'];
}

/*$url_arr=explode('.', $_SERVER['HTTP_HOST']);
if(!CSite::InDir('/catalog/'.$url_arr[0].'/')) LocalRedirect('https://erosite.top'.$APPLICATION->GetCurPage(false));*/
?><?$APPLICATION->IncludeComponent(
	"bitrix:catalog", 
	"erotic_massage_page", 
	array(
		"ACTION_VARIABLE" => "action",
		"ADD_ELEMENT_CHAIN" => "N",
		"ADD_PICT_PROP" => "-",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BASKET_URL" => "/personal/basket.php",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "N",
		"COMPATIBLE_MODE" => "Y",
		"DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
		"DETAIL_BACKGROUND_IMAGE" => "-",
		"DETAIL_BRAND_USE" => "N",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
		"DETAIL_DETAIL_PICTURE_MODE" => array(
			0 => "MAGNIFIER",
		),
		"DETAIL_DISPLAY_NAME" => "Y",
		"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
		"DETAIL_IMAGE_RESOLUTION" => "16by9",
		"DETAIL_MAIN_BLOCK_PROPERTY_CODE" => array(
		),
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_PRODUCT_INFO_BLOCK_ORDER" => "sku,props",
		"DETAIL_PRODUCT_PAY_BLOCK_ORDER" => "rating,price,priceRanges,quantityLimit,quantity,buttons",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_SHOW_POPULAR" => "Y",
		"DETAIL_SHOW_SLIDER" => "N",
		"DETAIL_SHOW_VIEWED" => "Y",
		"DETAIL_STRICT_SECTION_CHECK" => "Y",
		"DETAIL_USE_COMMENTS" => "N",
		"DETAIL_USE_VOTE_RATING" => "N",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "PROPERTY_PACK_SERVICE.PROPERTY_FOR_SORT",
		"ELEMENT_SORT_FIELD2" => "PROPERTY_DAY_PAY",
		"ELEMENT_SORT_ORDER2" => "asc,nulls",
		"ELEMENT_SORT_ORDER" => "desc,nulls",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_HIDE_ON_MOBILE" => "N",
		"FILTER_NAME" => "",
		"FILTER_PRICE_CODE" => array(
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_VIEW_MODE" => "HORIZONTAL",
		"IBLOCK_ID" => "7",
		"IBLOCK_TYPE" => "girls",
		"INCLUDE_SUBSECTIONS" => "Y",
		"INSTANT_RELOAD" => "N",
		"LABEL_PROP" => array(
		),
		"LABEL_PROP_MOBILE" => "",
		"LABEL_PROP_POSITION" => "top-left",
		"LAZY_LOAD" => "N",
		"LINE_ELEMENT_COUNT" => "3",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"LINK_IBLOCK_ID" => "",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_PROPERTY_SID" => "",
		"LIST_BROWSER_TITLE" => "UF_TITLE",
		"LIST_ENLARGE_PRODUCT" => "STRICT",
		"LIST_META_DESCRIPTION" => "UF_DESCRIPTION",
		"LIST_META_KEYWORDS" => "-",
		"LIST_PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
		"LIST_PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
		"LIST_PROPERTY_CODE" => array(
			0 => "user_id",
			1 => "METRO",
			2 => "RAION",
			3 => "ADRESS",
			4 => "ADRESS2",
			5 => "ADRESS3",
			6 => "ADRESS4",
			7 => "ADRESS5",
			8 => "ADRESS6",
			9 => "ADRESS7",
			10 => "ADRESS8",
			11 => "ADRESS9",
			12 => "ADRESS10",
			13 => "AAAA2",
			14 => "AAAA3",
			15 => "AAAA1",
			16 => "FACEBOOK",
			17 => "INSTAGRAMM",
			18 => "WIFI",
			19 => "uslugi",
			20 => "TIME_RAB",
			21 => "CITY",
			22 => "DOP",
			23 => "ZAMETKA",
			24 => "KOL_ZV_DAY_01",
			25 => "KOL_ZV_DAY_10",
			26 => "KOL_ZV_DAY_11",
			27 => "KOL_ZV_DAY_12",
			28 => "KOL_ZV_DAY_13",
			29 => "KOL_ZV_DAY_14",
			30 => "KOL_ZV_DAY_15",
			31 => "KOL_ZV_DAY_16",
			32 => "KOL_ZV_DAY_17",
			33 => "KOL_ZV_DAY_18",
			34 => "KOL_ZV_DAY_19",
			35 => "KOL_ZV_DAY_02",
			36 => "KOL_ZV_DAY_20",
			37 => "KOL_ZV_DAY_21",
			38 => "KOL_ZV_DAY_22",
			39 => "KOL_ZV_DAY_23",
			40 => "KOL_ZV_DAY_24",
			41 => "KOL_ZV_DAY_25",
			42 => "KOL_ZV_DAY_26",
			43 => "KOL_ZV_DAY_27",
			44 => "KOL_ZV_DAY_28",
			45 => "KOL_ZV_DAY_29",
			46 => "KOL_ZV_DAY_03",
			47 => "KOL_ZV_DAY_30",
			48 => "KOL_ZV_DAY_31",
			49 => "KOL_ZV_DAY_04",
			50 => "KOL_ZV_DAY_05",
			51 => "KOL_ZV_DAY_06",
			52 => "KOL_ZV_DAY_07",
			53 => "KOL_ZV_DAY_08",
			54 => "KOL_ZV_DAY_09",
			55 => "LIKE_1",
			56 => "LIKE_10",
			57 => "LIKE_11",
			58 => "LIKE_12",
			59 => "LIKE_13",
			60 => "LIKE_14",
			61 => "LIKE_15",
			62 => "LIKE_16",
			63 => "LIKE_17",
			64 => "LIKE_18",
			65 => "LIKE_19",
			66 => "LIKE_2",
			67 => "LIKE_20",
			68 => "LIKE_21",
			69 => "LIKE_22",
			70 => "LIKE_23",
			71 => "LIKE_24",
			72 => "LIKE_25",
			73 => "LIKE_26",
			74 => "LIKE_27",
			75 => "LIKE_28",
			76 => "LIKE_29",
			77 => "LIKE_3",
			78 => "LIKE_30",
			79 => "LIKE_31",
			80 => "LIKE_4",
			81 => "LIKE_5",
			82 => "LIKE_6",
			83 => "LIKE_7",
			84 => "LIKE_8",
			85 => "LIKE_9",
			86 => "Phone",
			87 => "OB_KOL_ZV",
			88 => "PAY_CART",
			89 => "MAPS_GOOGLE",
			90 => "PACK_SERVICE",
			91 => "LIST_PRICE",
			92 => "SITE",
			93 => "TEXT_ACTION",
			94 => "TYPE_PAY",
			95 => "MAPS_YANDEX",
			96 => "MONY",
			97 => "EMAIL",
			98 => "AKCII",
			99 => "BAR",
			100 => "VIDEO",
			101 => "VMESTIMOST",
			102 => "DJAKUZI",
			103 => "KALNYAN",
			104 => "OPLATA_BEZNAL",
			105 => "PROGRAMS",
			106 => "SAUNA",
			107 => "PRICE_MIN",
			108 => "EMAIL_KON_LIC",
			109 => "KON_LIC",
			110 => "TEL_KON_LIC",
			111 => "DAY_PAY",
			112 => "VHOD_VL",
			113 => "",
		),
		"LIST_PROPERTY_CODE_MOBILE" => array(
		),
		"LIST_SHOW_SLIDER" => "Y",
		"LIST_SLIDER_INTERVAL" => "3000",
		"LIST_SLIDER_PROGRESS" => "N",
		"LOAD_ON_SCROLL" => "N",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_COMPARE" => "Сравнение",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "round",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "30",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(
		),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"SEARCH_CHECK_DATES" => "Y",
		"SEARCH_NO_WORD_LOGIC" => "Y",
		"SEARCH_PAGE_RESULT_COUNT" => "50",
		"SEARCH_RESTART" => "N",
		"SEARCH_USE_LANGUAGE_GUESS" => "Y",
		"SECTIONS_SHOW_PARENT_NAME" => "Y",
		"SECTIONS_VIEW_MODE" => "LIST",
		"SECTION_BACKGROUND_IMAGE" => "-",
		"SECTION_COUNT_ELEMENTS" => "Y",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_TOP_DEPTH" => "2",
		"SEF_FOLDER" => "/erotic_massage/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "Y",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_DEACTIVATED" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_TOP_ELEMENTS" => "N",
		"SIDEBAR_DETAIL_POSITION" => "right",
		"SIDEBAR_DETAIL_SHOW" => "N",
		"SIDEBAR_PATH" => "",
		"SIDEBAR_SECTION_POSITION" => "right",
		"SIDEBAR_SECTION_SHOW" => "Y",
		"TEMPLATE_THEME" => "blue",
		"TOP_ELEMENT_COUNT" => "9",
		"TOP_ELEMENT_SORT_FIELD" => "sort",
		"TOP_ELEMENT_SORT_FIELD2" => "id",
		"TOP_ELEMENT_SORT_ORDER" => "asc",
		"TOP_ELEMENT_SORT_ORDER2" => "desc",
		"TOP_ENLARGE_PRODUCT" => "STRICT",
		"TOP_LINE_ELEMENT_COUNT" => "3",
		"TOP_PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
		"TOP_PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
		"TOP_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_PROPERTY_CODE_MOBILE" => "",
		"TOP_SHOW_SLIDER" => "Y",
		"TOP_SLIDER_INTERVAL" => "3000",
		"TOP_SLIDER_PROGRESS" => "N",
		"TOP_VIEW_MODE" => "SECTION",
		"USER_CONSENT" => "N",
		"USER_CONSENT_ID" => "0",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "N",
		"USE_COMPARE" => "N",
		"USE_ELEMENT_COUNTER" => "Y",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"USE_FILTER" => "Y",
		"USE_MAIN_ELEMENT_SECTION" => "Y",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"USE_STORE" => "N",
		"COMPONENT_TEMPLATE" => "catalog_subdomen",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "",
			"element" => "#ELEMENT_ID#/",
			"compare" => "compare.php?action=#ACTION_CODE#",
			"smart_filter" => "#SECTION_ID#/#SMART_FILTER_PATH#/apply/",
		),
		"VARIABLE_ALIASES" => array(
			"compare" => array(
				"ACTION_CODE" => "action",
			),
		)
	),
	false
);?>
<?/*<script>
	BX.addCustomEvent("onAfterSetCity", function(city, city_id, full_name){   
	    var link=$('.footer_sity_block a:contains("'+city+'")').attr('href');
	    location.href=link;
	});
</script>*/?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>